heartbeat.monitors:
- type: http
  schedule: '@every 30s'
  urls:
    - https://vg.no

- type: icmp
  schedule: '@every 30s'
  hosts:
    - yahoo.com

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"
