trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: docker-compose build
  displayName: 'Docker build'

- script: |
    docker login --username $dockerId --password $pswd
    docker push
  displayName: 'Docker push'
  env:
    pswd: $(dockerPassword)
    dockerId: $(dockerId)