trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: 'chudinov'

steps:
- script: docker-compose build
  displayName: 'Docker build'

- script: |
    docker login --username $(dockerId) --password $pswd
    docker push $(dockerId)/$(imageName)
  displayName: 'Docker push'
  env:
    pswd: $(dockerPassword)
    