version: '3.7'

services:
  elasticsearch:
    image: chudinov/elasticsearch
    container_name: elasticsearch
    networks: ['elastic']
    restart: always
    build:
      context: './elasticsearch'    
    # environment:
    #     - discovery.type=single-node
    #     - network.host=elasticsearch
    
  kibana:
    image: chudinov/kibana
    container_name: kibana
    ports: ['5601:80']
    networks: ['elastic']
    restart: always
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=6.7.0
    depends_on: ['elasticsearch']
    
  heartbeat:
    image: chudinov/heartbeat
    container_name: heartbeat
    networks: ['elastic']
    restart: always
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=6.7.0
    depends_on: ['elasticsearch','kibana']

networks:
  elastic:
    name: elastic
    driver: bridge
