version: '3.7'

services:
  elasticsearch:
    image: chudinov/elasticsearch
    container_name: elasticsearch
    ports: ['9200:9200'.'9300:9300']
    networks: ['elastic']
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"    
    build:
      context: './elasticsearch'
      args:
        - IMAGE_VERSION=7.0.0    
    
  kibana:
    image: chudinov/kibana
    container_name: kibana
    ports: ['5601:80']
    networks: ['elastic']
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=7.0.0
    depends_on: ['elasticsearch']

  heartbeat:
    image: chudinov/heartbeat
    container_name: heartbeat
    networks: ['elastic']
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=7.0.0
    depends_on: ['elasticsearch']

networks:
  elastic:
    name: elastic
    driver: bridge
    