version: '3.7'

services:
  elastic:
    image: ${ELASTICSEARCH_IMAGE_NAME}:${ELASTICSEARCH_IMAGE_VERSION}
    container_name: elastic
    networks: 
      elastic:
    
  kibana:
    image: ${KIBANA_IMAGE_NAME}
    container_name: kibana
    ports:
      - 5601:80
    networks: 
      elastic:
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=${KIBANA_IMAGE_VERSION}

  heartbeat:
    image: ${HEARTBEAT_IMAGE_NAME}
    container_name: heartbeat
    networks: 
      elastic:
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=${HEARTBEAT_IMAGE_VERSION}

networks:
  elastic:
    name: elastic
    driver: bridge
    