version: '3.7'

services:
  elasticsearch:
    image: chudinov/elasticsearch
    container_name: elasticsearch
    networks: ['elastic']
    restart: always
    build:
      context: './elasticsearch'
      args:
        - IMAGE_VERSION=7.0.0 
    
  kibana:
    image: chudinov/kibana
    container_name: kibana
    networks: ['elastic']
    restart: always
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=7.0.0
    
  heartbeat:
    image: chudinov/heartbeat
    container_name: heartbeat
    networks: ['elastic']
    restart: always
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=7.0.0
    depends_on: ['kibana']

  nginx:
    image: chudinov/elasticnginx
    container_name: nginx
    ports: ['80:80']
    networks: ['elastic']
    restart: always
    build: 
      context: './nginx'
    depends_on: ['elasticsearch','kibana']

networks:
  elastic:
    name: elastic
    driver: bridge
