version: '3.7'

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE_NAME}
    container_name: elasticsearch    
    #ports: ['9200:9200','9300:9300']
    networks:
      elastic:
        ipv4_address: 10.4.71.15
    build:
      context: './elasticsearch'
      args:
        - IMAGE_VERSION=${ELASTICSEARCH_IMAGE_VERSION}
    environment:
        - discovery.type=single-node
        - network.host=elasticsearch
    
  kibana:
    image: ${KIBANA_IMAGE_NAME}
    container_name: kibana
    ports: ['5601:5601']
    networks: ['elastic']
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=${KIBANA_IMAGE_VERSION}
    depends_on: ['elasticsearch']

  heartbeat:
    image: ${HEARTBEAT_IMAGE_NAME}
    container_name: heartbeat
    networks: ['elastic']
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=${HEARTBEAT_IMAGE_VERSION}
    depends_on: ['elasticsearch','kibana']

networks:
  elastic:
    name: elastic
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.71.0/24
