version: '3.7'

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE_NAME}
    container_name: elasticsearch
    networks: ['elastic']
    restart: always
    build:
      context: './elasticsearch'
      args:
        - IMAGE_VERSION=${ELASTICSEARCH_IMAGE_VERSION}
    #environment:
        #- discovery.type=single-node
        #- network.host=elasticsearch
    
  kibana:
    image: ${KIBANA_IMAGE_NAME}
    container_name: kibana
    ports: ['8083:5601']
    restart: always
    networks: ['elastic']
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=${KIBANA_IMAGE_VERSION}
    depends_on: ['elasticsearch']

  heartbeat:
    image: ${HEARTBEAT_IMAGE_NAME}
    container_name: heartbeat
    networks: ['elastic']
    restart: always
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=${HEARTBEAT_IMAGE_VERSION}
    depends_on: ['elasticsearch','kibana']

networks:
  elastic:
    name: elastic
    driver: bridge
