version: '3.7'

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE_NAME}
    container_name: elasticsearch    
    #ports: ['9200:9200','9300:9300']   #no need for this
    networks:
      elastic:
        ipv4_address: 172.20.0.3
    build:
      context: './elasticsearch'
      args:
        - IMAGE_VERSION=${ELASTICSEARCH_IMAGE_VERSION}
    environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    
  kibana:
    image: ${KIBANA_IMAGE_NAME}
    container_name: kibana
    ports: ['5601:80']
    networks: ['elastic']
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=${KIBANA_IMAGE_VERSION}
    depends_on: ['elasticsearch']

  heartbeat:
    image: ${HEARTBEAT_IMAGE_NAME}
    container_name: heartbeat
    networks: ['elastic']
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=${HEARTBEAT_IMAGE_VERSION}
    depends_on: ['elasticsearch']

networks:
  elastic:
    name: elastic
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

    