version: '3.7'

services:
  elasticsearch:
    image: chudinov/elasticsearch
    container_name: elasticsearch
    ports: ['9200:9200']
    networks: ['elastic']
    build:
      context: './elasticsearch'
      args:
        - IMAGE_VERSION=7.0.0    
    environment:
        - discovery.type=single-node
        - network.host=elasticsearch
    
  kibana:
    image: chudinov/kibana
    container_name: kibana
    ports: ['5601:80']
    networks: ['elastic']
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=7.0.0
    depends_on: ['elasticsearch']
    
  heartbeat:
    image: chudinov/heartbeat
    container_name: heartbeat
    networks: ['elastic']
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=7.0.0
    depends_on: ['elasticsearch','kibana']

networks:
  elastic:
    name: elastic
    driver: bridge
