version: '3.7'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    container_name: elastic
    networks: 
      elastic:
    
  kibana:
    image: chudinov/kibana
    container_name: kibana
    ports:
      - 5601:5601
    networks: 
      elastic:
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=6.7.1

  heartbeat:
    image: chudinov/heartbeat
    container_name: heartbeat
    networks: 
      elastic:
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=6.7.1

networks:
  elastic:
    name: elastic
    driver: bridge
    