version: '3.7'

services:
  # elasticsearch:
  #   image: chudinov/elasticsearch
  #   container_name: elasticsearch
  #   networks: ['elastic']
  #   restart: always
  #   build:
  #     context: './elasticsearch'    
    
  kibana:
    image: chudinov/kibana
    container_name: kibana
    ports: ['80:80']
    networks: ['elastic']
    restart: always
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=6.7.1
    environment:
        - server.port=80
        - elasticsearch.hosts="http://52.155.172.120:9200"
    
  heartbeat:
    image: chudinov/heartbeat
    container_name: heartbeat
    networks: ['elastic']
    restart: always
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=6.7.1
    depends_on: ['kibana']
    environment:
        - setup.kibana.host="kibana:80"
        - output.elasticsearch.hosts="52.155.172.120:9200"

networks:
  elastic:
    name: elastic
    driver: bridge
