version: '3.7'

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE_NAME}
    container_name: elasticsearch
    networks: ['elastic']
    restart: always
    build:
      context: './elasticsearch'
      args:
        - IMAGE_VERSION=${KIBANA_IMAGE_VERSION}
    
  kibana:
    image: ${KIBANA_IMAGE_NAME}
    container_name: kibana
    networks: ['elastic']
    restart: always
    build:
      context: './kibana'
      args:
        - IMAGE_VERSION=${KIBANA_IMAGE_VERSION}
    depends_on: ['elasticsearch']

  heartbeat:
    image: ${HEARTBEAT_IMAGE_NAME}
    container_name: heartbeat
    networks: ['elastic']
    restart: always
    build: 
      context: './heartbeat'
      args:
        - IMAGE_VERSION=${HEARTBEAT_IMAGE_VERSION}
    depends_on: ['elasticsearch','kibana']

  nginx:
    image: chudinov/elasticnginx
    container_name: nginx
    ports: ['8081:80']
    networks: ['elastic']
    restart: always
    build: 
      context: './nginx'
    depends_on: ['elasticsearch','kibana']

networks:
  elastic:
    name: elastic
    driver: bridge
