setup.kibana.host: ["kibana:5601"]
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
  
metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 60s
    enabled: true

  - module: elasticsearch
    metricsets:
      - node
      - node_stats
    period: 60s
    hosts: ["http://elasticsearch:9200"]

  - module: system
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      - socket_summary  # Socket summary
      - diskio         # Disk IO
      - filesystem     # File system usage for each mountpoint
      - fsstat         # File system summary metrics
      - service        # systemd service information
    enabled: true
    period: 10s
    processes: ['.*']      
    cpu.metrics:  ["percentages"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  # username: '${ELASTICSEARCH_USERNAME:}'
  # password: '${ELASTICSEARCH_PASSWORD:}'